# Generated by Django 4.0.4 on 2022-04-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiuser',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
