# Generated by Django 4.0.4 on 2022-04-21 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers_app', '0002_alter_follower_follower_id_alter_follower_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folowee', to=settings.AUTH_USER_MODEL),
        ),
    ]
