# Generated by Django 4.0.4 on 2022-04-14 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('top_3_attractions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('image', models.CharField(max_length=250)),
            ],
        ),
    ]
