# Generated by Django 4.0.4 on 2022-04-16 20:56

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
