# Generated by Django 4.0.4 on 2022-04-16 21:07

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0002_auto_20220416_2056'),
    ]

    operations = [
        UnaccentExtension()
    ]
