# Generated by Django 4.0.4 on 2022-04-21 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_app', '0004_alter_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='travellers',
            field=models.ManyToManyField(blank=True, related_name='city', to=settings.AUTH_USER_MODEL),
        ),
    ]
