# Generated by Django 4.0.4 on 2022-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0005_city_travellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='travellers',
        ),
    ]
