# Generated by Django 4.0.4 on 2022-04-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_app', '0006_remove_city_travellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to=settings.AUTH_USER_MODEL),
        ),
    ]
