# Generated by Django 4.0.4 on 2022-04-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0008_rename_user_city_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='users',
        ),
    ]
