# Generated by Django 4.0.4 on 2022-04-20 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_app', '0004_alter_city_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews_app', '0003_alter_review_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=7, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='cities_app.city')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday', to='reviews_app.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
