# Generated by Django 4.0.4 on 2022-04-21 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0005_city_travellers'),
        ('reviews_app', '0003_alter_review_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holidays_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='cities_app.city'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to='reviews_app.review'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to=settings.AUTH_USER_MODEL),
        ),
    ]
