# Generated by Django 4.0.4 on 2022-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays_app', '0002_alter_holiday_city_alter_holiday_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='review',
        ),
    ]
